# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "37376cd1ff9c1786a37220311fd9b4f1"
name = "Al Recommendation "
application_url = "https://ai-recommendation-project-production.up.railway.app/shopify"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [
  "https://ai-recommendation-project-production.up.railway.app/shopify/callback"
]
